package com.credvenn.lm.applicationvariable;
import com.credvenn.lm.application.LoanRequestApplicationRepository;import com.credvenn.lm.common.exception.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ApplicationVariableService{final ApplicationVariableDefinitionRepository defs;final ApplicationVariableRepository values;final LoanRequestApplicationRepository apps;final ObjectMapper json;public ApplicationVariableService(ApplicationVariableDefinitionRepository d,ApplicationVariableRepository v,LoanRequestApplicationRepository a,ObjectMapper j){defs=d;values=v;apps=a;json=j;}
@Transactional(readOnly=true) public List<DefinitionResponse> schema(String t){return defs.findAllByTenantIdAndActiveTrueOrderByDisplayOrderAsc(t).stream().map(this::out).toList();}
@Transactional public DefinitionResponse create(String t,DefinitionRequest r){if(defs.existsByTenantIdAndCodeIgnoreCase(t,r.code().trim()))throw new ConflictException("Application variable code already exists");if(r.fieldType()==ApplicationVariableFieldType.SINGLE_SELECT&&(r.options()==null||r.options().isEmpty()))throw new BadRequestException("SINGLE_SELECT requires options");ApplicationVariableDefinition d=new ApplicationVariableDefinition();d.tenantId=t;d.code=r.code().trim().toUpperCase(Locale.ROOT);d.label=r.label().trim();d.sectionName=clean(r.sectionName());d.fieldType=r.fieldType();d.required=r.required();d.displayOrder=r.displayOrder()==null?0:r.displayOrder();try{d.optionsJson=json.writeValueAsString(r.options()==null?List.of():r.options());}catch(Exception e){throw new BadRequestException("Invalid options");}return out(defs.save(d));}
@Transactional public List<AnswerResponse> save(String t,String app,List<AnswerRequest> input){apps.findByIdAndTenantId(app,t).orElseThrow(()->new NotFoundException("Application not found"));List<AnswerRequest> a=input==null?List.of():input;Map<String,AnswerRequest> by=new HashMap<>();for(var x:a)if(by.put(x.definitionId(),x)!=null)throw new BadRequestException("Duplicate application variable answer");List<ApplicationVariableDefinition> active=defs.findAllByTenantIdAndActiveTrueOrderByDisplayOrderAsc(t);for(var d:active)if(d.required&&!by.containsKey(d.id))throw new BadRequestException("Required application variable is missing: "+d.code);List<ApplicationVariable> saved=new ArrayList<>();for(var x:a){var d=defs.findByIdAndTenantId(x.definitionId(),t).filter(z->z.active).orElseThrow(()->new BadRequestException("Unknown or inactive application variable"));String v=x.value()==null?null:x.value().trim();if(v==null||v.isBlank())throw new BadRequestException("Answer is required for "+d.code);validate(d,v);ApplicationVariable av=new ApplicationVariable();av.tenantId=t;av.applicationId=app;av.definitionId=d.id;av.code=d.code;av.label=d.label;av.section=d.sectionName;av.fieldType=d.fieldType;av.value=v;saved.add(values.save(av));}return saved.stream().map(this::out).toList();}
@Transactional(readOnly=true) public List<AnswerResponse> answers(String t,String app){apps.findByIdAndTenantId(app,t).orElseThrow(()->new NotFoundException("Application not found"));return values.findAllByTenantIdAndApplicationId(t,app).stream().map(this::out).toList();}
void validate(ApplicationVariableDefinition d,String v){try{switch(d.fieldType){case INTEGER->Integer.parseInt(v);case DECIMAL,MONEY->new BigDecimal(v);case DATE->LocalDate.parse(v);case BOOLEAN->{if(!v.equalsIgnoreCase("true")&&!v.equalsIgnoreCase("false"))throw new Exception();}case SINGLE_SELECT->{List<String> o=json.readValue(d.optionsJson,new TypeReference<>(){});if(o.stream().noneMatch(v::equals))throw new Exception();}default->{}}}catch(Exception e){throw new BadRequestException("Invalid value for "+d.code);}}
DefinitionResponse out(ApplicationVariableDefinition d){List<String> o;try{o=json.readValue(d.optionsJson,new TypeReference<>(){});}catch(Exception e){o=List.of();}return new DefinitionResponse(d.id,d.code,d.label,d.sectionName,d.fieldType,d.required,d.active,d.displayOrder,o);}AnswerResponse out(ApplicationVariable v){return new AnswerResponse(v.definitionId,v.code,v.label,v.section,v.fieldType,v.value);}String clean(String v){return v==null||v.isBlank()?null:v.trim();}
public record DefinitionRequest(String code,String label,String sectionName,ApplicationVariableFieldType fieldType,boolean required,Integer displayOrder,List<String> options){}public record DefinitionResponse(String id,String code,String label,String sectionName,ApplicationVariableFieldType fieldType,boolean required,boolean active,int displayOrder,List<String> options){}public record AnswerRequest(String definitionId,String value){}public record AnswerResponse(String definitionId,String code,String label,String sectionName,ApplicationVariableFieldType fieldType,String value){}
}
