package com.credvenn.lm.application;

public enum ApplicationStatus {
    SUBMITTED,
    PENDING_KYC,
    KYC_IN_PROGRESS,
    KYC_FAILED,
    KYC_MANUAL_REVIEW,
    KYC_PASSED_CLIENT_CREATED,
    STATEMENT_PENDING,
    STATEMENT_IN_PROGRESS,
    STATEMENT_FAILED,
    STATEMENT_MANUAL_REVIEW,
    STATEMENT_VERIFIED,
    OFFERS_READY,
    OFFER_SELECTED,
    CONSENT_CAPTURED,
    INTERNAL_APPROVED,
    FINERACT_LOAN_CREATED_PENDING_DEVICE,
    DEVICE_ASSIGNMENT_FAILED,
    DEVICE_ASSIGNED,
    FINERACT_LOAN_ACTIVATED,
    REJECTED
}
